### ISSUE TITLE
Failed to activate the python-indent package

### ISSUE THREAD

**Issue by b3ni** [DSpeckhals/python-indent#10] opened 2016-02-25 06:48 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Ubuntu 15.10
**Thrown From**: [python-indent](https://github.com/DSpeckhals/python-indent) package, v0.3.4
### Stack Trace

Failed to activate the python-indent package

```
At PythonIndent is not a function

TypeError: PythonIndent is not a function
    at Object.module.exports.activate (/home/b3ni/.atom/packages/python-indent/lib/main.coffee:27:25)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:181:20)
    at /usr/share/atom/resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:526:21)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -0:18.8.0 project-viewer:toggle (atom-pane.pane.active)
     -0:12.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "color-picker",
      "emmet",
      "linter-pep8"
    ],
    "ignoredNames": [
      ".git"
    ],
    "packagesWithKeymapsDisabled": [
      "language-php",
      "highlight-selected"
    ],
    "projectHome": "/home/b3ni/workspace",
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "python-indent": {}
}
```
### Installed Packages

``` coffee
# User
django-atom, v0.2.4
file-icons, v1.6.15
highlight-selected, v0.11.2
linter, v1.11.3
minimap, v4.19.0
monokai, v0.18.0
project-viewer, v0.2.31
python-indent, v0.3.4
react, v0.14.1

# Dev
No dev packages
```

**Comment by DSpeckhals** [comment] 2016-02-25 12:47
I can't reproduce this on Windows. I will try Ubuntu in a few hours. My only guess right now is that I published a major update (mostly refactoring) of the package last night, and your updated is somehow half-baked.

Does this still happen after you reload Atom?

**Comment by EntilZha** [comment] 2016-02-25 17:38
I ran into the same thing after the update, quitting/restarting Atom seemed to fix it

**Comment by DSpeckhals** [comment] 2016-02-25 18:53
Yeah...that would make sense. There was a lot of moving code around; specifically, the `activate` function that Atom uses to start up the package was changed in the manifest. I think that would do it. I'm going to close this for now, but feel free to report back if there continues to be an issue.

**Closed as completed by DSpeckhals** 2016-02-25 18:53 UTC

**Comment by thedrow** [comment] 2016-02-28 09:47
I have this issue as well with Mac OSX.

**Comment by ngaurav** [comment] 2016-03-01 06:26
me too experiencing it on os x

**Comment by AnayaBit** [comment] 2016-03-01 19:29
me too  on Ubuntu :(

**Comment by Doooooo0o** [comment] 2016-03-03 16:00
+1 on fedora

**Comment by DSpeckhals** [comment] 2016-03-04 13:49
One thing I'm curious about is how long of a time there was between instances of opening Atom? Are we talking a couple of weeks? A few days? I ask because there was a major update to the package a few weeks ago, and I could see how that would cause this package to not start properly after the update, but be fine afterwards. I cannot recreate this issue.

**Comment by wouterdebie** [comment] 2016-04-14 12:01
I just ran into this issue when updating to 1.7.0.

**Comment by DSpeckhals** [comment] 2016-04-14 12:03
Does it work after you restart Atom?

**Comment by wouterdebie** [comment] 2016-04-14 12:04
Yeah, works :) thanks
