### ISSUE TITLE
De-dent is broken on break/continue/yield/raise/return

### ISSUE THREAD

**Issue by duckpuppy** [DSpeckhals/python-indent#50] opened 2017-09-27 15:44 UTC
I am using 1.1.1 of python-indent and atom 1.20.1 on OSX.  The following code results in this:
```python
def test():
    while True:
        if True:
            break
    else:|
```
Expected results should be:
```python
def test():
    while True:
        if True:
            break
        else:|
```
This is probably because of the de-dent change here: https://github.com/atom/language-python/pull/140

It seems that both language-python and python-indent are de-denting when they encounter an item in that list of keywords, resulting in a double de-dent.

**Comment by kbrose** [comment] 2017-09-28 08:51
Not quite - this package does not dedent in that situation. The problem is that the language-python dedents after seeing `break`, and then again on `else:`. I do think that the problem will need to be fixed from this package though, since Atom's built-in indentation API does not have sufficient capabilities (namely the ability to look at the previous line to effect the current line's indentation) to handle it. It's on my list of things to do, but right now I'm pretty crunched for time. This package is not that large and should be well documented if you want to submit a PR for it, though.

(BTW what you linked to was closed without merging. The actual PR is https://github.com/atom/language-python/pull/204 where someone raised the same issue you have here.)

**Comment by kbrose** [comment] 2017-10-11 14:04
@DSpeckhals any thoughts on the best way to handle this?

Right now I'm thinking of, after newline is entered, check if previous _previous_ row (`row - 2`) satisfies the `decreaseNextIndentPattern` pattern and if the previous row (`row - 1`) satisfies `decreaseIndentPattern`, then we increase the indentation of the previous row and the current row to offset the changes.

The reason I'm not 100% sold on this is b/c it will still show a dedent after you finish typing `else:` (for example), but before you hit the newline, so it would take some training/documentation to inform people that they could still hit enter and it would be corrected after.

I think if we wanted to do it immediately, we would have to be observing each character entry instead of just newlines?

**Comment by DSpeckhals** [comment] 2017-10-11 15:35
@kbrose I understand the situation, but the problem, as you've mentioned, is complicated. I would be curious to find out what the fix looks like in practice. I think your solution works, but I'm not quite sure about looking back too many lines and trying to figure out what to do; but then again, I guess that's just the nature of Python's syntax.

I don't think that it would be intuitive to do this for a user after the dedent is showing unexpectedly. They'd have to dig into the documentation to find that it will correct for them. I would imagine that most people will just manually correct the indentation if it's wrong after typing `:`. Sure, we could implement the functionality you explain; but will people take advantage of it? I have my doubts.

I have to admit that I don't like the idea of evaluating after each key press. That makes the package a little too complicated IMHO.

**Comment by kbrose** [comment] 2017-10-11 15:48
Generally in agreement with you. Although I was envisioning running a much smaller function on every keypress, but keeping the other behavior (the one that requires parsing the whole file) on every newline. This smaller function would only be trying to match regexes on two lines, so it shouldn't be too heavy computationally. I don't know if that helps address your concerns or not...

(Also, matching regexes after every keypress is what Atom already does, at least two times in fact. Once to do their own automatic indentation seeing if the line of code matches the indent regexes, which they do on every key press as can be seen by the fact that `else:` dedents as soon as you finish typing it, and another time to get syntax highlighting which is also defined as a huge regex.)

**Comment by kbrose** [comment] 2018-04-12 20:13
I think this is closed by more recent versions of Atom reverting the above-linked PR to `language-python`.

**Comment by DSpeckhals** [comment] 2018-04-13 18:32
@kbrose I'll close this then.

**Closed as completed by DSpeckhals** 2018-04-13 18:32 UTC
